### ISSUE TITLE
Major issue when loading saved project

### ISSUE THREAD

**Issue by binary-person** [chihuahua/beautiful-audio-editor#2]
I cannot get back into my locally saved project after I closed it. I am using Chrome 70 and the error in the console consists of this:
Uncaught DOMException: Failed to execute 'createBuffer' on 'BaseAudioContext': The number of frames provided (0) is less than or equal to the minimum bound (0).
    at Dp.<anonymous> (https://beautifulaudioeditor.appspot.com/js/c.js:336:228)
    at Ed (https://beautifulaudioeditor.appspot.com/js/c.js:48:69)
    at FileReader.Bd (https://beautifulaudioeditor.appspot.com/js/c.js:50:41)
    at FileReader.b (https://beautifulaudioeditor.appspot.com/js/c.js:46:50)
Any help appreciated!

**Comment by ConnorHalstead** [comment]
I had the same issue. FIX: Read https://beautifulaudioeditor.appspot.com/docs and install beautifulaudioeditor through google drive, this allows you to easily save and load your .audioproject files through google drive without a problem👍
